Update make rules for karabiner
- Add .envrc for loading homebrew in case it's not available in PATH
  (requires direnv)
- Update readme

diff --git a/karabiner/.config/karabiner/makefile b/karabiner/.config/karabiner/makefile
--- a/karabiner/.config/karabiner/makefile
+++ b/karabiner/.config/karabiner/makefile
@@ -7,29 +7,48 @@ target_dir := assets/complex_modifications
 targets := $(patsubst $(generator_dir)/%.jsonnet, %.json, $(generators))
 config := $(HOME)/.config/karabiner
 
-.PHONY: all init check install generate
+SHELL := /bin/bash
+
+.PHONY: all init check generate
+.SILENT: init check generate
 
 all: generate
 
-init: check generate
+init: check
 ifeq ($(PWD), $(config))
 else
-	command mv $(config) $(config)_backup
-	command ln -s $(PWD) $(config)
-	command launchctl kickstart -k gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server
+	if [[ ! -d $(config) ]]; then\
+		echo "Linking karabiner config to ~/.config/karabiner";\
+		command ln -s $(PWD) $(config);\
+	fi
+
+	if [[ -d "$(config)" ]] && [[ ! -L "$(config)" ]]; then\
+		echo "Existing karabiner config found inside ~/.config. Backup saved at ~/.config/karabiner_backup";\
+		command mv $(config) $(config)_backup;\
+		echo "Linking karabiner config to ~/.config/karabiner";\
+		command ln -s $(PWD) $(config);\
+	elif [[ -L "$(config)" ]] && [[ ! "$(shell readlink $(config))" -ef "$(PWD)" ]]; then\
+		printf '\n%s\n%s\n' "Existing karabiner config found inside ~/.config."\
+		"Not making any changes because it's a symlink. Remove or backup manually then proceed.";\
+	fi
 endif
 
-check: install
-	@brew $(brew_check_bundle)
-
-install:
-	@brew $(brew_check_bundle) 1>/dev/null || (\
-		echo 'Installing missing dependencies...';\
-		brew $(brew_install_bundle);\
-	)
+check:
+	read -p "Install dependencies with brew? [Y/n] " choice;\
+	case "$$choice" in\
+		Y | y | yes | Yes | YES)\
+			brew $(brew_check_bundle) 1>/dev/null || (\
+				echo "Installing missing dependencies...";\
+				brew $(brew_install_bundle);\
+			);\
+			;;\
+		*)\
+			exit 0;\
+			;;\
+	esac
 
 generate: $(targets)
-	@echo All targets are up-to-date
+	echo "All targets are up-to-date"
 
 $(targets): %.json: %.jsonnet
 
@@ -37,10 +56,10 @@ $(targets): %.json: %.jsonnet
 	$(eval target := $(target_dir)/$(@:.jsonnet=.json))
 	$(eval generator := $(generator_dir)/$@)
 
-	@if [ $(generator) -nt $(target) ]; then\
-		rm -rf $(target);\
-		echo Generating target for $@;\
-		jsonnet $(generator) -o $(target);\
-		karabiner_cli --lint-complex-modifications $(target);\
+	@if [[ "$(generator)" -nt "$(target)" ]]; then\
+		rm -rf "$(target)";\
+		echo "Generating target for $@";\
+		jsonnet "$(generator)" -o "$(target)";\
+		karabiner_cli --lint-complex-modifications "$(target)";\
 	fi
 
